name: build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      name: "math-parser"
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Configure Java 17
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: gradle check
        run: gradle check

      - name: gradle run test
        run: gradle test

      - name: gradle build
        run: gradle build

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*
          tag_name: 1.0.0
          name: math-parser-1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: gradle publish
        run: gradle publish
        env:
         USERNAME: ${{ github.actor }}
         TOKEN: ${{ secrets.GH_TOKEN }}



